name: Flutter Web CI

# This workflow is triggered on pushes to the repository.

on:
  push:
    branches:
    - main
    
# on: push    # Default will running for every branch.
    
jobs:
  build:
    # This job will run on ubuntu virtual machine
    runs-on: ubuntu-latest
    steps:
    
    - uses: actions/checkout@v2

    # Setup the flutter environment.
    - uses: subosito/flutter-action@v1
      with:
        channel: 'stable' # 'dev', 'alpha', default to: 'stable'
        flutter-version: '2.0.4' # you can also specify exact version of flutter
    
    # Get flutter dependencies.
    - name: Get project Dependencies
      run: flutter pub get
    
    # Check for any formatting issues in the code.
    # - run: flutter format --set-exit-if-changed .
    
    # Statically analyze the Dart code for any errors.
    # - run: flutter analyze .
    
    # Build apk.
    - name: Build Web
      run: flutter build web

    - name: Setup git config files
      run: |
        git config --global user.email "seeger.spencer[bot]@users.noreply.github.com"
        git config --global user.name "spenc53"

    - name: Push to build branch
      run: |
        cd build/web
        git init .
        git push -f https://${secrets.ACCESS_TOKEN}@github.com/spenc53/flutter-simple-weather.git